/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FILESERVER_H_RPCGEN
#define _FILESERVER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define FILESERVER 22222222
#define SIMP_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define getFile 1
extern  char ** getfile_1(char **, CLIENT *);
extern  char ** getfile_1_svc(char **, struct svc_req *);
extern int fileserver_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define getFile 1
extern  char ** getfile_1();
extern  char ** getfile_1_svc();
extern int fileserver_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FILESERVER_H_RPCGEN */
