/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "NameServer.h"

bool_t
xdr_register_operand (XDR *xdrs, register_operand *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->name, 128))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->hostname, 128))
		 return FALSE;
	return TRUE;
}
